templateDir: /local/generate/template
additionalProperties:
  artifactVersion: 1.0.0
  composerPackageName: synergitech/staffology-php
  developerOrganization: "Synergi Tech"
  developerOrganizationUrl: https://synergi.tech
  invokerPackage: SynergiTech\Staffology
  licenseName: MIT
  packageName: Staffology-PHP
  variableNamingConvention: camelCase
files:
  Configuration.mustache:
    templateType: SupportingFiles
    destinationFilename: src/Configuration.php
  ObjectSerializer.mustache:
    templateType: SupportingFiles
    destinationFilename: src/ObjectSerializer.php