<?php
/**
 * LgpsFund
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Staffology Payroll API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: duane@staffology.co.uk
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Staffology\Model;

/**
 * LgpsFund Class Doc Comment
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum LgpsFund: string
{
    case AVON = 'Avon';

    case BARKING_AND_DAGENHAM = 'BarkingAndDagenham';

    case BARNET = 'Barnet';

    case BEDFORDSHIRE = 'Bedfordshire';

    case BERKSHIRE = 'Berkshire';

    case BEXLEY = 'Bexley';

    case BRENT = 'Brent';

    case BROMLEY = 'Bromley';

    case BUCKINGHAMSHIRE = 'Buckinghamshire';

    case CAMBRIDGESHIRE = 'Cambridgeshire';

    case CAMDEN = 'Camden';

    case CARDIFF = 'Cardiff';

    case CHESHIRE = 'Cheshire';

    case CITY_OF_WESTMINSTER = 'CityOfWestminster';

    case CLWYD = 'Clwyd';

    case CORNWALL = 'Cornwall';

    case CROYDON = 'Croydon';

    case CUMBRIA = 'Cumbria';

    case DERBYSHIRE = 'Derbyshire';

    case DEVON = 'Devon';

    case DORSET = 'Dorset';

    case DURHAM = 'Durham';

    case DYFED = 'Dyfed';

    case EALING = 'Ealing';

    case EAST_RIDING = 'EastRiding';

    case EAST_SUSSEX = 'EastSussex';

    case ENFIELD = 'Enfield';

    case ESSEX = 'Essex';

    case GLOUCESTERSHIRE = 'Gloucestershire';

    case GREATER_GWENT = 'GreaterGwent';

    case GREATER_MANCHESTER = 'GreaterManchester';

    case GREENWICH = 'Greenwich';

    case GWYNEDD = 'Gwynedd';

    case HACKNEY = 'Hackney';

    case HAMMERSMITH_AND_FULHAM = 'HammersmithAndFulham';

    case HAMPSHIRE = 'Hampshire';

    case HARINGEY = 'Haringey';

    case HARROW = 'Harrow';

    case HAVERING = 'Havering';

    case HERTFORDSHIRE = 'Hertfordshire';

    case HILLINGDON = 'Hillingdon';

    case HOUNSLOW = 'Hounslow';

    case ISLE_OF_WIGHT = 'IsleOfWight';

    case ISLINGTON = 'Islington';

    case KENSINGTON_AND_CHELSEA = 'KensingtonAndChelsea';

    case KENT = 'Kent';

    case KINGSTON_UPON_THAMES = 'KingstonUponThames';

    case LAMBETH = 'Lambeth';

    case LANCASHIRE = 'Lancashire';

    case LEICESTERSHIRE = 'Leicestershire';

    case LEWISHAM = 'Lewisham';

    case LINCOLNSHIRE = 'Lincolnshire';

    case LONDON_PENSIONS_FUND_AUTHORITY = 'LondonPensionsFundAuthority';

    case MERSEYSIDE = 'Merseyside';

    case MERTON = 'Merton';

    case NEWHAM = 'Newham';

    case NORFOLK = 'Norfolk';

    case NORTH_YORKSHIRE = 'NorthYorkshire';

    case NORTHAMPTONSHIRE = 'Northamptonshire';

    case NORTHUMBERLAND = 'Northumberland';

    case NOTTINGHAMSHIRE = 'Nottinghamshire';

    case OXFORDSHIRE = 'Oxfordshire';

    case POWYS = 'Powys';

    case REDBRIDGE = 'Redbridge';

    case RHONDDA_CYNON_TAF = 'RhonddaCynonTaf';

    case SHROPSHIRE = 'Shropshire';

    case SOMERSET = 'Somerset';

    case SOUTH_YORKSHIRE = 'SouthYorkshire';

    case SOUTHWARK = 'Southwark';

    case STAFFORDSHIRE = 'Staffordshire';

    case SUFFOLK = 'Suffolk';

    case SURREY = 'Surrey';

    case SUTTON = 'Sutton';

    case SWANSEA = 'Swansea';

    case TEESSIDE = 'Teesside';

    case TOWER_HAMLETS = 'TowerHamlets';

    case TYNE_AND_WEAR = 'TyneAndWear';

    case WALTHAM_FOREST = 'WalthamForest';

    case WANDSWORTH = 'Wandsworth';

    case WARWICKSHIRE = 'Warwickshire';

    case WEST_MIDLANDS_PASSENGER_TRANSPORT = 'WestMidlandsPassengerTransport';

    case WEST_MIDLANDS = 'WestMidlands';

    case WEST_SUSSEX = 'WestSussex';

    case WEST_YORKSHIRE = 'WestYorkshire';

    case WILTSHIRE = 'Wiltshire';

    case WORCESTERSHIRE = 'Worcestershire';
}


