<?php
/**
 * NiLetterValidationReportLine
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Staffology Payroll API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: duane@staffology.co.uk
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Staffology\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use SynergiTech\Staffology\ObjectSerializer;

/**
 * NiLetterValidationReportLine Class Doc Comment
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class NiLetterValidationReportLine implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'NiLetterValidationReportLine';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'employeeId' => 'string',
        'payrollCode' => 'string',
        'name' => 'string',
        'niNumber' => 'string',
        'gender' => '\SynergiTech\Staffology\Model\Gender',
        'dateOfBirth' => '\DateTime',
        'niLetterError' => '\SynergiTech\Staffology\Model\NiLetterError',
        'errorDetails' => 'string',
        'niLetter' => 'string',
        'suggestedLetter' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'employeeId' => 'uuid',
        'payrollCode' => null,
        'name' => null,
        'niNumber' => null,
        'gender' => null,
        'dateOfBirth' => 'date',
        'niLetterError' => null,
        'errorDetails' => null,
        'niLetter' => null,
        'suggestedLetter' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'employeeId' => false,
        'payrollCode' => true,
        'name' => true,
        'niNumber' => true,
        'gender' => false,
        'dateOfBirth' => false,
        'niLetterError' => false,
        'errorDetails' => true,
        'niLetter' => true,
        'suggestedLetter' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'employeeId' => 'employeeId',
        'payrollCode' => 'payrollCode',
        'name' => 'name',
        'niNumber' => 'niNumber',
        'gender' => 'gender',
        'dateOfBirth' => 'dateOfBirth',
        'niLetterError' => 'niLetterError',
        'errorDetails' => 'errorDetails',
        'niLetter' => 'niLetter',
        'suggestedLetter' => 'suggestedLetter'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'employeeId' => 'setEmployeeId',
        'payrollCode' => 'setPayrollCode',
        'name' => 'setName',
        'niNumber' => 'setNiNumber',
        'gender' => 'setGender',
        'dateOfBirth' => 'setDateOfBirth',
        'niLetterError' => 'setNiLetterError',
        'errorDetails' => 'setErrorDetails',
        'niLetter' => 'setNiLetter',
        'suggestedLetter' => 'setSuggestedLetter'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'employeeId' => 'getEmployeeId',
        'payrollCode' => 'getPayrollCode',
        'name' => 'getName',
        'niNumber' => 'getNiNumber',
        'gender' => 'getGender',
        'dateOfBirth' => 'getDateOfBirth',
        'niLetterError' => 'getNiLetterError',
        'errorDetails' => 'getErrorDetails',
        'niLetter' => 'getNiLetter',
        'suggestedLetter' => 'getSuggestedLetter'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('employeeId', $data ?? [], null);
        $this->setIfExists('payrollCode', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('niNumber', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('dateOfBirth', $data ?? [], null);
        $this->setIfExists('niLetterError', $data ?? [], null);
        $this->setIfExists('errorDetails', $data ?? [], null);
        $this->setIfExists('niLetter', $data ?? [], null);
        $this->setIfExists('suggestedLetter', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets employeeId
     *
     * @return string|null
     */
    public function getEmployeeId(): ?string
    {
        return $this->container['employeeId'];
    }

    /**
     * Sets employeeId
     *
     * @param string|null $employeeId employeeId
     *
     * @return $this
     */
    public function setEmployeeId(?string $employeeId): static
    {
        if (is_null($employeeId)) {
            throw new InvalidArgumentException('non-nullable employeeId cannot be null');
        }
        $this->container['employeeId'] = $employeeId;

        return $this;
    }

    /**
     * Gets payrollCode
     *
     * @return string|null
     */
    public function getPayrollCode(): ?string
    {
        return $this->container['payrollCode'];
    }

    /**
     * Sets payrollCode
     *
     * @param string|null $payrollCode payrollCode
     *
     * @return $this
     */
    public function setPayrollCode(?string $payrollCode): static
    {
        if (is_null($payrollCode)) {
            array_push($this->openAPINullablesSetToNull, 'payrollCode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('payrollCode', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['payrollCode'] = $payrollCode;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets niNumber
     *
     * @return string|null
     */
    public function getNiNumber(): ?string
    {
        return $this->container['niNumber'];
    }

    /**
     * Sets niNumber
     *
     * @param string|null $niNumber niNumber
     *
     * @return $this
     */
    public function setNiNumber(?string $niNumber): static
    {
        if (is_null($niNumber)) {
            array_push($this->openAPINullablesSetToNull, 'niNumber');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('niNumber', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['niNumber'] = $niNumber;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return \SynergiTech\Staffology\Model\Gender|null
     */
    public function getGender(): ?\SynergiTech\Staffology\Model\Gender
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param \SynergiTech\Staffology\Model\Gender|null $gender gender
     *
     * @return $this
     */
    public function setGender(?\SynergiTech\Staffology\Model\Gender $gender): static
    {
        if (is_null($gender)) {
            throw new InvalidArgumentException('non-nullable gender cannot be null');
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets dateOfBirth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth(): ?\DateTime
    {
        return $this->container['dateOfBirth'];
    }

    /**
     * Sets dateOfBirth
     *
     * @param \DateTime|null $dateOfBirth dateOfBirth
     *
     * @return $this
     */
    public function setDateOfBirth(?\DateTime $dateOfBirth): static
    {
        if (is_null($dateOfBirth)) {
            throw new InvalidArgumentException('non-nullable dateOfBirth cannot be null');
        }
        $this->container['dateOfBirth'] = $dateOfBirth;

        return $this;
    }

    /**
     * Gets niLetterError
     *
     * @return \SynergiTech\Staffology\Model\NiLetterError|null
     */
    public function getNiLetterError(): ?\SynergiTech\Staffology\Model\NiLetterError
    {
        return $this->container['niLetterError'];
    }

    /**
     * Sets niLetterError
     *
     * @param \SynergiTech\Staffology\Model\NiLetterError|null $niLetterError niLetterError
     *
     * @return $this
     */
    public function setNiLetterError(?\SynergiTech\Staffology\Model\NiLetterError $niLetterError): static
    {
        if (is_null($niLetterError)) {
            throw new InvalidArgumentException('non-nullable niLetterError cannot be null');
        }
        $this->container['niLetterError'] = $niLetterError;

        return $this;
    }

    /**
     * Gets errorDetails
     *
     * @return string|null
     */
    public function getErrorDetails(): ?string
    {
        return $this->container['errorDetails'];
    }

    /**
     * Sets errorDetails
     *
     * @param string|null $errorDetails errorDetails
     *
     * @return $this
     */
    public function setErrorDetails(?string $errorDetails): static
    {
        if (is_null($errorDetails)) {
            array_push($this->openAPINullablesSetToNull, 'errorDetails');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('errorDetails', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['errorDetails'] = $errorDetails;

        return $this;
    }

    /**
     * Gets niLetter
     *
     * @return string|null
     */
    public function getNiLetter(): ?string
    {
        return $this->container['niLetter'];
    }

    /**
     * Sets niLetter
     *
     * @param string|null $niLetter niLetter
     *
     * @return $this
     */
    public function setNiLetter(?string $niLetter): static
    {
        if (is_null($niLetter)) {
            array_push($this->openAPINullablesSetToNull, 'niLetter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('niLetter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['niLetter'] = $niLetter;

        return $this;
    }

    /**
     * Gets suggestedLetter
     *
     * @return string|null
     */
    public function getSuggestedLetter(): ?string
    {
        return $this->container['suggestedLetter'];
    }

    /**
     * Sets suggestedLetter
     *
     * @param string|null $suggestedLetter suggestedLetter
     *
     * @return $this
     */
    public function setSuggestedLetter(?string $suggestedLetter): static
    {
        if (is_null($suggestedLetter)) {
            array_push($this->openAPINullablesSetToNull, 'suggestedLetter');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('suggestedLetter', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['suggestedLetter'] = $suggestedLetter;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


