<?php
/**
 * Report
 *
 * PHP version 8.1
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Staffology Payroll API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: duane@staffology.co.uk
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SynergiTech\Staffology\Model;

/**
 * Report Class Doc Comment
 *
 * @package  SynergiTech\Staffology
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum Report: string
{
    case GROSS_TO_NET = 'GrossToNet';

    case GROSS_TO_NET_CIS = 'GrossToNetCis';

    case PAYRUN_PAYMENTS = 'PayrunPayments';

    case FURLOUGH = 'Furlough';

    case PENSION_CONTRIBS = 'PensionContribs';

    case JOURNAL = 'Journal';

    case HOURLY_PAY = 'HourlyPay';

    case UMBRELLA_RECONCILIATION = 'UmbrellaReconciliation';

    case UMBRELLA_STATEMENT = 'UmbrellaStatement';

    case STATUTORY_PAY = 'StatutoryPay';

    case COST_ANALYSIS = 'CostAnalysis';

    case COST_OF_EMPLOYMENT = 'CostOfEmployment';

    case FULL_SUMMARY_OF_PAY = 'FullSummaryOfPay';

    case P11 = 'P11';

    case P11D = 'P11d';

    case P30 = 'P30';

    case P32 = 'P32';

    case P45 = 'P45';

    case P60 = 'P60';

    case EMPLOYEE_EXPORT = 'EmployeeExport';

    case RIGHT_TO_WORK = 'RightToWork';

    case AEO_STATEMENT = 'AeoStatement';

    case HOLIDAY_ALLOWANCES = 'HolidayAllowances';

    case HOLIDAY_PAY_ACCRUALS = 'HolidayPayAccruals';

    case AE_ASSESSMENTS = 'AeAssessments';

    case CIS_STATEMENT = 'CisStatement';

    case SUBCONTRACTOR_SUMMARY = 'SubcontractorSummary';

    case PAYROLL_ANALYSIS = 'PayrollAnalysis';

    case VARIANCE_REPORT = 'VarianceReport';

    case P11_DETAILED = 'P11Detailed';

    case NI_LETTER_VALIDATION = 'NiLetterValidation';

    case YTD = 'Ytd';

    case TAX_CODE_CHANGES = 'TaxCodeChanges';

    case EMPLOYEE_BENEFITS = 'EmployeeBenefits';

    case MEMBER_ENROLMENT = 'MemberEnrolment';

    case ATTACHMENT_ORDERS = 'AttachmentOrders';

    case NI_YTD = 'NiYtd';

    case APPRENTICESHIP_LEVY = 'ApprenticeshipLevy';

    case TEACHERS_PENSION_EOY = 'TeachersPensionEoy';

    case MATERNITY_SCHEDULE = 'MaternitySchedule';

    case PAY_SPINE = 'PaySpine';

    case SPINE_POINT = 'SpinePoint';

    case PAY_GRADES = 'PayGrades';

    case PAY_SPINE_ALLOWANCES = 'PaySpineAllowances';

    case AVERAGE_HOLIDAY_PAY_RATE = 'AverageHolidayPayRate';

    case EMPLOYEE_ROLE_EXPORT = 'EmployeeRoleExport';

    case HOLIDAY_PAY_ACCRUALS_HOURS = 'HolidayPayAccrualsHours';

    case GENDER_PAY_GAP = 'GenderPayGap';

    case PENSION_MEMBERSHIPS = 'PensionMemberships';

    case PAY_ELEMENT = 'PayElement';

    case LOAN_BALANCES = 'LoanBalances';

    case EMPLOYEE_LEAVE = 'EmployeeLeave';

    case ADVANCED_VARIANCE_REPORT = 'AdvancedVarianceReport';
}


